
# GENERAL SETTING
data_root: 'data/demo'
output_dir: 'output/demo'
model_type: 'XL'
size: 1024
device: 'cuda'

# GENERATE
source_prompt: 'A hobbit wearing robes' # CHANGE HERE, MAKE SURE IT CONTAINS THE BASE WORD
base_condition: 'hobbit' # CHANGE HERE
neg_prompt: ''
steps: 30
guidance_scale: 7.5
g_seed: 6543
gen_base: 10 # Generate auxiliary images

# TUNE
concept_type: 'character'  # CHANGE HERE, choose from 'character' 'object' 'style'
seed: 999
lr: 0.0001
neg_num: 3 # Auxiliary images used in a batch
lambda1: 0.5
lambda2: 0.2
batch_size: 1 # Fixed
epochs: 1
save_steps: 10
checkpointing_steps: 500
resume_from_checkpoint: None  # True or None
xt_to_use: -1

# env config
use_xformers: True
allow_tf32: True